//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affairdetails
    {
        public int id { get; set; }
        public Nullable<int> generalTransactionRangeId { get; set; }
        public string itemTypeName { get; set; }
        public Nullable<int> transactionOrgTypeId { get; set; }
        public string itemBasicCode { get; set; }
        public string spObjectName { get; set; }
        public string depCateName { get; set; }
        public Nullable<int> legalPeriod { get; set; }
        public string version { get; set; }
        public Nullable<int> orgId { get; set; }
        public string itemImpleCode { get; set; }
        public string orgCode { get; set; }
        public string name { get; set; }
        public string exeTierName { get; set; }
        public string isNetPay { get; set; }
        public Nullable<int> transactionFormId { get; set; }
        public string isNetAppointment { get; set; }
        public Nullable<int> promisePeriod { get; set; }
        public string dealItemName { get; set; }
        public string itemTransactionResult { get; set; }
        public Nullable<int> supervisionCount { get; set; }
        public string isInternetPublic { get; set; }
        public string itemTypeCode { get; set; }
        public string orgName { get; set; }
        public string businessTypeName { get; set; }
        public Nullable<int> privUpdateTypeId { get; set; }
        public string relieveWay { get; set; }
        public string transactionTime { get; set; }
        public Nullable<int> transactionLevelId { get; set; }
        public string isInvestmentProject { get; set; }
        public Nullable<int> transactionTypeId { get; set; }
        public string isExpress { get; set; }
        public int VALID { get; set; }
        public string isFee { get; set; }
        public string feeName { get; set; }
        public string feeNorm { get; set; }
        public string feeGist { get; set; }
        public string feeLink { get; set; }
        public string feeTime { get; set; }
        public string feeAddress { get; set; }
        public string feeReduce { get; set; }
        public string SEPCIALVERSION { get; set; }
    }
}
