//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affairguidetemp
    {
        public int id { get; set; }
        public Nullable<int> affairdetailsid { get; set; }
        public string unacceptCondition { get; set; }
        public string approveRange { get; set; }
        public string superviseWay { get; set; }
        public string dutyInfo { get; set; }
        public string acceptCondition { get; set; }
        public string approveCondition { get; set; }
        public string accountabilityInfo { get; set; }
        public string consultWay { get; set; }
        public string itemCommonProcess { get; set; }
        public string transactionSite { get; set; }
        public string unapproveCondition { get; set; }
        public string setGist { get; set; }
        public string acceptRange { get; set; }
        public string accountabilityGist { get; set; }
        public string faq { get; set; }
        public string limitNum { get; set; }
    }
}
