//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GxsdEntities : DbContext
    {
        public GxsdEntities()
            : base("name=GxsdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<deptinfo> deptinfo { get; set; }
        public DbSet<materials> materials { get; set; }
        public DbSet<affairstemp> affairstemp { get; set; }
        public DbSet<dic_dictionarydto> dic_dictionarydto { get; set; }
        public DbSet<affairguidetemp> affairguidetemp { get; set; }
        public DbSet<affairdetails> affairdetails { get; set; }
        public DbSet<areainfo> areainfo { get; set; }
    }
}
